MouseBehaviour:
    normalize: true
    batch_size: 64
    buffer_size: 12000
    summary_freq: 1000
    time_horizon: 1000
    lambd: 0.99
    beta: 0.001
    max_steps: 10.0e5
    trainer: ppo
    epsilon: 0.2
    hidden_units: 128
    learning_rate: 3.0e-4
    learning_rate_schedule: linear
    memory_size: 256
    normalize: false
    num_epoch: 3
    num_layers: 2
    sequence_length: 64
    summary_freq: 1000
    use_recurrent: false
    vis_encode_type: simple
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99

